### ISSUE TITLE
Migrar a Jetpack Navigation 

### ISSUE THREAD

**Issue by ImanolOlveira** [carlos-mg89/flickrgallery#33]

**Comment by carlos-mg89** [comment]
@ImanolOlveira estoy llegando a esta lección del módulo 3, justo he acabado ahora de verme la del DataBinding. Seguramente la veré ahora la del Navigation Component. Supongo que entre hoy y mañana me haré una buena idea de qué es exactamente el Navigation Component y de lo que necesitaríamos realizar en el proyecto. 

Pero te agradecería que redactases una lista de cambios / tareas que tocaría realizar para ver si lo podemos dividir en issues separadas. ¿Lo ves factible o prefieres que organicemos una reunión?
