### ISSUE TITLE
Localizaciones guardadas

### ISSUE THREAD

**Issue by adria88** [carlos-mg89/flickrgallery#5]
- ~~**Lista de localizaciones guardadas**~~
- ~~**Eliminar localización**~~
- **Enlazar a lista de fotos**: crear ExploreFragment que cargue las fotos de la localización seleccionada

**Comment by carlos-mg89** [comment]
Aviso de que ya tengo esta tarea prácticamente terminada.

**Comment by carlos-mg89** [comment]
Falta enlazar StoredLocationsFragment con un nuevo ExploreFragment que coja fotos del ViewModel.

Quien quiera puede continuar con esta tarea.
